### ISSUE TITLE
captureException() fails with HTTP Status Code 413

### ISSUE THREAD

**Issue by arabold** [getsentry/raven-node#153] opened 2016-05-07 18:00 UTC
I'm browserify & minify my code base into a single huge JS with just a few lines of code (but many, many characters per line obviously). While the code itself works fine, it fails to upload any captured exception to getsentry.com with HTTP Status Code 413.

I could nail it down to the minification. If I'm running the unminified version (still one huge JS file, but this time with many lines of code) then POSTing the exception works as expected. I'm guessing that the reason is that Raven tries to submit callstack information and gets thrown off by the fact that pretty much everything is in a single line of code.

In an ideal world I want to upload my source map to Sentry and have Raven-Node/Sentry figure the rest out. Or maybe I should use `raven-js` instead of `raven-node` although I'm running server-side?

**Comment by mattrobenolt** [comment] 2016-05-07 18:12
That's definitely the problem. We also don't even support source maps for node. That's exclusively a browser JavaScript feature for us now. 

Since this is a bit confusing to me, can you share some context on why you'd do this for a Node deployment in the first place?

**Comment by arabold** [comment] 2016-05-07 18:16
https://github.com/arabold/serverless-sentry-plugin -- this is why :)

We're developing projects for AWS Lambda using the popular [Serverless](https://github.com/serverless/serverless) framework. For AWS Lambda it is common to browserify and minify the code base as it improves loading time. The link above is for a plugin that automatically instructs your code to report errors to Sentry.

**Comment by scottgeye** [comment] 2017-04-17 00:07
Running into the same issue.  Any update or work around for this? 

Thanks!

**Comment by sid137** [comment] 2017-05-16 13:07
just got bit by this too...   4 hrs of life...

**Comment by LewisJEllis** [comment] 2017-05-16 18:10
@sid137 sorry to hear that :(

I'll look into this more today, especially since it seems we'll have more folks with long single lines after the recent webpack compatibility workaround in v2.0.0 and the generally increasing popularity of lambda.

Sourcemap support is a relevant topic here, and it's on the roadmap, but it's definitely a bigger undertaking and we don't consider it to be quite *as* crucial of a feature as it is in the browser, for a number of reasons. A fix for the 413 problem specifically should be pretty straightforward, hopefully just a "if line longer than x, truncate" check.

**Comment by kamilogorek** [comment] 2017-09-20 12:15
Fixed in https://github.com/getsentry/raven-node/commit/8e111ffd1be85ac18e51f446c05ede9f513171cc#diff-50e3aa130a4f97a42ee2cf111c7b1d9d

Also confirmed that stack size for raw express.js app, bundled with browserify and uglifyjs is below 50kb, which fits easily into payload limit.

<img width="1436" alt="screen shot 2017-09-20 at 14 14 06" src="https://user-images.githubusercontent.com/1523305/30643191-35a8baea-9e0e-11e7-8ad3-b4addb4a8aa2.png">

**Closed** 2017-09-20 12:16 UTC
