### ISSUE TITLE
GMT express deprecated req.host: Use req.hostname instead at node_modules\raven\lib\parsers.js:84:19

### ISSUE THREAD

**Issue by Freundschaft** [getsentry/raven-node#117] opened 2015-05-12 22:58 UTC
I get this warning as soon as ravenJS triggers

**Comment by mattrobenolt** [comment] 2015-05-12 22:59
This is a duplicate of https://github.com/getsentry/raven-node/pull/101 which has been pulled.

**Closed by mattrobenolt** 2015-05-12 22:59 UTC

**Comment by Freundschaft** [comment] 2015-05-12 23:38
sorry, I didnt see that, cheers!
