### ISSUE TITLE
Is it possible to get it to work with Restify

### ISSUE THREAD

**Issue by maheshoml** [getsentry/raven-node#291] opened 2017-03-09 18:37 UTC
I tried using this with Restify (Node, restify.com). While `.install()` works fine and reports startup errors, if any.

Using `Raven.errorHandler()` causes requests to the app hang and eventually timeout. Does not happen when I use only `Raven.requestHandler()` but in that case no errors are reported to the Sentry server.

**Comment by LewisJEllis** [comment] 2017-03-13 23:00
This is roughly a duplicate of #287; for now, I'd follow the recommendation given there. The `errorHandler` and `requestHandler` middleware are made for express and express-like middleware stacks, but restify is a bit different. I'll move restify up the todo list considering the interest.

**Closed by LewisJEllis** 2017-03-13 23:00 UTC

**Comment by maheshoml** [comment] 2017-03-14 08:24
Thanks @LewisJEllis. For now, I am calling the error handling middleware from raven manually in Restify's own error handler.

Also, do you know of any memory leak issues caused by Raven (node v0.10.x)? Since after we deployed raven our instance memory is going over the roof every few hours. Seems like it could be linked to TLS leak issue. I am still investigating and not sure if I should open a new issue at this stage.

**Comment by LewisJEllis** [comment] 2017-03-14 20:35
@maheshoml I'm not aware of any; relevant question in #286, but not an issue as far as I can tell. We've done some memory usage testing for functionality that might be prone to leaking memory, but I don't have much long-running real-world memory usage data to compare to. If you have any detailed info on any potential memory leaks, please let me know so I can investigate.

**Comment by arvalaan** [comment] 2017-05-18 11:13
@LewisJEllis I'm also interested in using Raven with Restify. Is there any way we can tell where Restify is on said todo list?

**Comment by awesomehimanshu** [comment] 2017-09-27 07:01
@arvalaan i have done by this.
restify 6.0.1

var Raven = require("raven");
Raven.config("--yourdsnofraven--").install();

when server created add this `handleUncaughtExceptions`.

global.server = restify.createServer({
    handleUncaughtExceptions: true
});

// capture error here
server.on("uncaughtException", function (req, res, route, err)  {
    "use strict";
    console.log("i caught it!");
    Raven.captureException(err, {req: req});
    res.send(new httpErrors.InternalServerError(CONFIG.error_message.INTERNAL_SERVER_ERROR));
});
