### ISSUE TITLE
Safe async exit after an exception

### ISSUE THREAD

**Issue by simonepri** [getsentry/raven-node#354] opened 2017-08-01 19:32 UTC
## Problem
There's no way to know if is safe to kill the process or if raven is sending data.

### Scenario
Imagine that somewere in the code I want to kill my server, but in the meanwhile raven is sending some data to Sentry. 

# Workaround
```
let exceptions = 0;
process.on('uncaughtException', () => {
    exceptions++;
});

raven
    .config(dns, opts)
    .install(handler); // Since we have passed a custom handler the process does not exit automatically, this is good :)

function handler(err) {
  exceptions--;
  // Log the erro on the console
  console.log(err);
}

function close(cb) {
  const interval = setInterval(closed, 100);
    closed();

    function closed() {
      if (exceptions === 0) {
        clearInterval(interval);
        cb();
      }
    }
  });
}


// Somewhere else
close(() => {
  // This is called after all errors are been sent to sentry. Now you can kill the process safetly.
  process.exit(1);
});
```

**Comment by kamilogorek** [comment] 2018-01-23 12:33
Duplicate of https://github.com/getsentry/raven-node/issues/338

**Closed by kamilogorek** 2018-01-23 12:33 UTC
